name: ASH Security Scan with PR Comments

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py
            **/*.js
            **/*.ts
            **/*.java
            **/*.go
            **/*.rb
            **/*.php
            **/*.cs
            **/*.cpp
            **/*.c
            **/*.h
            **/*.yaml
            **/*.yml
            **/*.json
            **/*.sh
            **/*.dockerfile
            **/Dockerfile*
            **/requirements*.txt
            **/package*.json
            **/Pipfile*
            **/pom.xml
            **/build.gradle*
            **/*.tf
            **/*.tfvars

      - name: Set up Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ASH
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pip install git+https://github.com/awslabs/automated-security-helper.git@v3.0.0

      - name: Create temp directory for changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          mkdir -p /tmp/ash-scan
          echo "Changed files for security scan:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n'

      - name: Copy changed files to temp directory
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f "$file" ]; then
              mkdir -p "/tmp/ash-scan/$(dirname "$file")"
              cp "$file" "/tmp/ash-scan/$file"
              echo "Copied for scan: $file"
            fi
          done

      - name: Run ASH scan on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd /tmp/ash-scan
          ash --mode container 2>&1 | tee /tmp/ash-output.log
        continue-on-error: true

      - name: Process scan results and create summary
        if: steps.changed-files.outputs.any_changed == 'true'
        id: process-results
        run: |
          SUMMARY_FILE="/tmp/pr_comment.md"
          
          if [ -f "/tmp/ash-output.log" ]; then
            # Find the table boundaries  
            TABLE_START=$(grep -n "ASH Scan Results Summary" /tmp/ash-output.log | head -1 | cut -d: -f1 || echo "0")
            TABLE_END=$(grep -n "source-dir:" /tmp/ash-output.log | head -1 | cut -d: -f1 || echo "0")
            
            echo "## Security Scan Results" > "$SUMMARY_FILE"
            echo "" >> "$SUMMARY_FILE"
            
            if [ "$TABLE_START" != "0" ] && [ "$TABLE_END" != "0" ] && [ "$TABLE_END" -gt "$TABLE_START" ]; then
              # Add scan metadata and explanation
              echo "### Scan Metadata" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "- **Project**: ASH" >> "$SUMMARY_FILE"
              echo "- **Scan executed**: $(date -u +%Y-%m-%dT%H:%M:%S+00:00)" >> "$SUMMARY_FILE"
              echo "- **ASH version**: 3.0.0" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              
              echo "### Summary" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "#### Scanner Results" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "The table below shows findings by scanner, with status based on severity thresholds and dependencies:" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "**Severity levels:**" >> "$SUMMARY_FILE"
              echo "- **Suppressed (S)**: Findings that have been explicitly suppressed and don't affect scanner status" >> "$SUMMARY_FILE"
              echo "- **Critical (C)**: Highest severity findings that require immediate attention" >> "$SUMMARY_FILE"
              echo "- **High (H)**: Serious findings that should be addressed soon" >> "$SUMMARY_FILE"
              echo "- **Medium (M)**: Moderate risk findings" >> "$SUMMARY_FILE"
              echo "- **Low (L)**: Lower risk findings" >> "$SUMMARY_FILE"
              echo "- **Info (I)**: Informational findings with minimal risk" >> "$SUMMARY_FILE"
              echo "- **Duration (Time)**: Time taken by the scanner to complete its execution" >> "$SUMMARY_FILE"
              echo "- **Actionable**: Number of findings at or above the threshold severity level that require attention" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "**Result:**" >> "$SUMMARY_FILE"
              echo "- **PASSED** = No findings at or above threshold" >> "$SUMMARY_FILE"
              echo "- **FAILED** = Findings at or above threshold" >> "$SUMMARY_FILE"
              echo "- **MISSING** = Required dependencies not available" >> "$SUMMARY_FILE"
              echo "- **SKIPPED** = Scanner explicitly disabled" >> "$SUMMARY_FILE"
              echo "- **ERROR** = Scanner execution error" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "**Threshold**: The minimum severity level that will cause a scanner to fail" >> "$SUMMARY_FILE"
              echo "- Thresholds: ALL, LOW, MEDIUM, HIGH, CRITICAL" >> "$SUMMARY_FILE"
              echo "- Source: Values in parentheses indicate where the threshold is set:" >> "$SUMMARY_FILE"
              echo "  - **global** (global_settings section in the ASH_CONFIG used)" >> "$SUMMARY_FILE"
              echo "  - **config** (scanner config section in the ASH_CONFIG used)" >> "$SUMMARY_FILE"
              echo "  - **scanner** (default configuration in the plugin, if explicitly set)" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "**Statistics calculation:**" >> "$SUMMARY_FILE"
              echo "- All statistics are calculated from the final aggregated SARIF report" >> "$SUMMARY_FILE"
              echo "- Suppressed findings are counted separately and do not contribute to actionable findings" >> "$SUMMARY_FILE"
              echo "- Scanner status is determined by comparing actionable findings to the threshold" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              
              # Convert terminal table to markdown table format
              echo "| Scanner | S | C | H | M | L | I | Time | Action | Result | Thresh |" >> "$SUMMARY_FILE"
              echo "|---------|---|---|---|---|---|---|------|--------|--------|--------|" >> "$SUMMARY_FILE"
              # Extract table data, strip ANSI codes, and convert to markdown
              sed -n "${TABLE_START},${TABLE_END}p" /tmp/ash-output.log | \
              sed 's/\x1b\[[0-9;]*m//g' | \
              grep "^│" | \
              sed 's/│/|/g' | \
              sed 's/^ *|/|/' | \
              sed 's/| *$/|/' >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              
              # Add detailed findings
              if [ -f "/tmp/ash-scan/.ash/ash_output/reports/ash.summary.md" ]; then
                grep -A 1000 "Detailed Findings" "/tmp/ash-scan/.ash/ash_output/reports/ash.summary.md" | \
                grep -v -E '^(Time since scan:|Report generated:)' | \
                grep -v 'Report generated by Automated Security Helper' >> "$SUMMARY_FILE" || true
              fi
            else
              # Fallback to markdown report if terminal extraction fails
              if [ -f "/tmp/ash-scan/.ash/ash_output/reports/ash.summary.md" ]; then
                grep -v -E '^(Time since scan:|Report generated:)' "/tmp/ash-scan/.ash/ash_output/reports/ash.summary.md" | \
                grep -v 'Report generated by Automated Security Helper' > "$SUMMARY_FILE"
              fi
            fi
            
            # Check if findings were detected
            if grep -q "Actionable findings detected!" /tmp/ash-output.log; then
              echo "has_findings=true" >> $GITHUB_OUTPUT
            else
              echo "has_findings=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "## Security Scan Results" > "$SUMMARY_FILE"
            echo "" >> "$SUMMARY_FILE"
            echo "No security scan results found." >> "$SUMMARY_FILE"
            echo "has_findings=false" >> $GITHUB_OUTPUT
          fi
          

      - name: Upload ASH results
        if: steps.changed-files.outputs.any_changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: ash-security-results
          path: |
            /tmp/ash-scan/.ash/
            /tmp/pr_comment.md
          retention-days: 30

      - name: Add PR comment
        if: steps.changed-files.outputs.any_changed == 'true'
        # Always run this step even if ASH scan failed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const commentPath = '/tmp/pr_comment.md';
            
            if (fs.existsSync(commentPath)) {
              const commentBody = fs.readFileSync(commentPath, 'utf8');
              const issueNumber = context.issue.number;
              
              // Check if we already commented
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
              });
              
              const botComment = comments.find(comment => 
                comment.user.type === 'Bot' && 
                comment.body.includes('Security Scan Results')
              );
              
              // Add commit info to the body
              const commitSha = context.payload.pull_request?.head?.sha || context.sha;
              const enhancedBody = `**Latest scan for commit:** \`${commitSha.substring(0, 7)}\`\n\n${commentBody}`;
              
              if (botComment) {
                // Update existing comment with latest scan
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: enhancedBody
                });
                console.log('Updated existing ASH security scan comment');
              } else {
                // Create new comment
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  body: enhancedBody
                });
                console.log('Created new ASH security scan comment');
              }
            }

      - name: Security scan summary
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ "${{ steps.process-results.outputs.has_findings }}" = "true" ]; then
            echo "Security findings detected. Please review the results."
            # Note: Currently configured to NOT fail the workflow on security findings
            # Uncomment the next line to enforce strict security policy
            # exit 1
          else
            echo "No security issues found in the changed files."
          fi

      - name: Skip message
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No relevant files changed - skipping security scan"