name: ASH Security Scan with PR Comments

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py
            **/*.js
            **/*.ts
            **/*.java
            **/*.go
            **/*.rb
            **/*.php
            **/*.cs
            **/*.cpp
            **/*.c
            **/*.h
            **/*.yaml
            **/*.yml
            **/*.json
            **/*.sh
            **/*.dockerfile
            **/Dockerfile*
            **/requirements*.txt
            **/package*.json
            **/Pipfile*
            **/pom.xml
            **/build.gradle*
            **/*.tf
            **/*.tfvars

      - name: Set up Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: astral-sh/setup-uv@v3

      - name: Install ASH
        if: steps.changed-files.outputs.any_changed == 'true'
        run: uv tool install git+https://github.com/awslabs/automated-security-helper.git@v3.0.0

      - name: Create temp directory for changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          mkdir -p /tmp/ash-scan
          echo "Changed files for security scan:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n'

      - name: Copy changed files to temp directory
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f "$file" ]; then
              mkdir -p "/tmp/ash-scan/$(dirname "$file")"
              cp "$file" "/tmp/ash-scan/$file"
              echo "Copied for scan: $file"
            fi
          done

      - name: Run ASH scan on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd /tmp/ash-scan
          uv tool run ash --mode local
        continue-on-error: true

      - name: Process scan results and create summary
        if: steps.changed-files.outputs.any_changed == 'true'
        id: process-results
        run: |
          SUMMARY_FILE="/tmp/pr_comment.md"
          
          echo "# 🔒 ASH Security Scan Results" > "$SUMMARY_FILE"
          echo "" >> "$SUMMARY_FILE"
          
          # Check if ASH results exist
          if [ -f "/tmp/ash-scan/.ash/ash_output/reports/ash.summary.md" ]; then
            echo "## Security Findings" >> "$SUMMARY_FILE"
            echo "" >> "$SUMMARY_FILE"
            cat "/tmp/ash-scan/.ash/ash_output/reports/ash.summary.md" >> "$SUMMARY_FILE"
            echo "" >> "$SUMMARY_FILE"
            echo "has_findings=true" >> $GITHUB_OUTPUT
          elif [ -d "/tmp/ash-scan/.ash" ]; then
            # Check for any findings in the output directory
            if find "/tmp/ash-scan/.ash" -name "*.json" -o -name "*.sarif" | grep -q .; then
              echo "⚠️ **Security scan completed with findings**" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "Please check the uploaded artifacts for detailed results." >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "has_findings=true" >> $GITHUB_OUTPUT
            else
              echo "✅ **No security issues detected in the changed files**" >> "$SUMMARY_FILE"
              echo "" >> "$SUMMARY_FILE"
              echo "has_findings=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "✅ **Security scan completed - no issues found**" >> "$SUMMARY_FILE"
            echo "" >> "$SUMMARY_FILE"
            echo "has_findings=false" >> $GITHUB_OUTPUT
          fi
          
          echo "## Files Scanned" >> "$SUMMARY_FILE"
          echo "" >> "$SUMMARY_FILE"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "- \`$file\`" >> "$SUMMARY_FILE"
          done
          
          echo "" >> "$SUMMARY_FILE"
          echo "---" >> "$SUMMARY_FILE"
          echo "*🤖 Automated security scan by [AWS ASH](https://github.com/awslabs/automated-security-helper)*" >> "$SUMMARY_FILE"

      - name: Upload ASH results
        if: steps.changed-files.outputs.any_changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: ash-security-results
          path: |
            /tmp/ash-scan/.ash/
            /tmp/pr_comment.md
          retention-days: 30

      - name: Add PR comment
        if: steps.changed-files.outputs.any_changed == 'true' && always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const commentPath = '/tmp/pr_comment.md';
            
            if (fs.existsSync(commentPath)) {
              const commentBody = fs.readFileSync(commentPath, 'utf8');
              const issueNumber = context.issue.number;
              
              // Check if we already commented
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
              });
              
              const botComment = comments.find(comment => 
                comment.user.type === 'Bot' && 
                comment.body.includes('🔒 ASH Security Scan Results')
              );
              
              if (botComment) {
                // Update existing comment
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: commentBody
                });
              } else {
                // Create new comment
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  body: commentBody
                });
              }
            }

      - name: Security scan summary
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ "${{ steps.process-results.outputs.has_findings }}" = "true" ]; then
            echo "⚠️ Security findings detected. Please review the results."
          else
            echo "✅ No security issues found in the changed files."
          fi

      - name: Skip message
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "ℹ️ No relevant files changed - skipping security scan"